# Generated by Django 3.2.6 on 2021-09-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todo'),
        ),
    ]
