# Generated by Django 3.2.6 on 2021-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_article_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
